
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kjfwyaniengzduyeeufq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtqZnd5YW5pZW5nemR1eWVldWZxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2MTA1NjcsImV4cCI6MjA1OTE4NjU2N30.LTlr7pbynAQz5UVK4gBuA_32gJ2hLVy3poQ-WcXHwOk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
      flowType: 'implicit'
    }
  }
);
